[package]
name = "atlas-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
atlas-parse = { path = "../atlas-parse" }
atlas-core = { path = "../atlas-core" }

reedline = "0.10.0"
nu-ansi-term = "0.46.0"

directories = "4.0.1"
dirs = "4.0.0"
clap = { version = "4.3.4", features = ["derive"] }
