[package]
name = "atlas-core"
version = "0.1.0"
authors = ["Daniel Pfrommer <dan.pfrommer@gmail.com>"]
edition = "2021"

[build-dependencies]
lalrpop = "0.19"
test-log = "0.2"

[dependencies]
log = "0.4.13"
pretty = "0.11"
slab = "0.4"
num_enum = "0.5"
async-trait = "0.1"
url = "2.2"
blocking = "1.2"
ordered-float = "2"
deadqueue = "=0.2.1"
bytes = "1.0"
smol = "1.2"
futures-lite = "1.12"
async-broadcast = "0.4"
curl = "0.4"
backtrace = "0.3"
